/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char123LocaleChar125RouteRouteImport } from './routes/{-$locale}/route'
import { Route as Char123LocaleChar125IndexRouteImport } from './routes/{-$locale}/index'
import { Route as Char123LocaleChar125TermsConditionsRouteImport } from './routes/{-$locale}/terms-conditions'
import { Route as Char123LocaleChar125ShinjiruRouteImport } from './routes/{-$locale}/shinjiru'
import { Route as Char123LocaleChar125Project9RouteImport } from './routes/{-$locale}/project9'
import { Route as Char123LocaleChar125PrivacyPolicyRouteImport } from './routes/{-$locale}/privacy-policy'
import { Route as Char123LocaleChar125ContactRouteImport } from './routes/{-$locale}/contact'
import { Route as Char123LocaleChar125AboutRouteImport } from './routes/{-$locale}/about'
import { Route as Char123LocaleChar125404RouteImport } from './routes/{-$locale}/404'
import { Route as Char123LocaleChar125SplatRouteImport } from './routes/{-$locale}/$'

const Char123LocaleChar125RouteRoute =
  Char123LocaleChar125RouteRouteImport.update({
    id: '/{-$locale}',
    path: '/{-$locale}',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125IndexRoute =
  Char123LocaleChar125IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125TermsConditionsRoute =
  Char123LocaleChar125TermsConditionsRouteImport.update({
    id: '/terms-conditions',
    path: '/terms-conditions',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125ShinjiruRoute =
  Char123LocaleChar125ShinjiruRouteImport.update({
    id: '/shinjiru',
    path: '/shinjiru',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125Project9Route =
  Char123LocaleChar125Project9RouteImport.update({
    id: '/project9',
    path: '/project9',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125PrivacyPolicyRoute =
  Char123LocaleChar125PrivacyPolicyRouteImport.update({
    id: '/privacy-policy',
    path: '/privacy-policy',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125ContactRoute =
  Char123LocaleChar125ContactRouteImport.update({
    id: '/contact',
    path: '/contact',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125AboutRoute =
  Char123LocaleChar125AboutRouteImport.update({
    id: '/about',
    path: '/about',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125404Route = Char123LocaleChar125404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => Char123LocaleChar125RouteRoute,
} as any)
const Char123LocaleChar125SplatRoute =
  Char123LocaleChar125SplatRouteImport.update({
    id: '/$',
    path: '/$',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/{-$locale}': typeof Char123LocaleChar125RouteRouteWithChildren
  '/{-$locale}/$': typeof Char123LocaleChar125SplatRoute
  '/{-$locale}/404': typeof Char123LocaleChar125404Route
  '/{-$locale}/about': typeof Char123LocaleChar125AboutRoute
  '/{-$locale}/contact': typeof Char123LocaleChar125ContactRoute
  '/{-$locale}/privacy-policy': typeof Char123LocaleChar125PrivacyPolicyRoute
  '/{-$locale}/project9': typeof Char123LocaleChar125Project9Route
  '/{-$locale}/shinjiru': typeof Char123LocaleChar125ShinjiruRoute
  '/{-$locale}/terms-conditions': typeof Char123LocaleChar125TermsConditionsRoute
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
}
export interface FileRoutesByTo {
  '/{-$locale}/$': typeof Char123LocaleChar125SplatRoute
  '/{-$locale}/404': typeof Char123LocaleChar125404Route
  '/{-$locale}/about': typeof Char123LocaleChar125AboutRoute
  '/{-$locale}/contact': typeof Char123LocaleChar125ContactRoute
  '/{-$locale}/privacy-policy': typeof Char123LocaleChar125PrivacyPolicyRoute
  '/{-$locale}/project9': typeof Char123LocaleChar125Project9Route
  '/{-$locale}/shinjiru': typeof Char123LocaleChar125ShinjiruRoute
  '/{-$locale}/terms-conditions': typeof Char123LocaleChar125TermsConditionsRoute
  '/{-$locale}': typeof Char123LocaleChar125IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/{-$locale}': typeof Char123LocaleChar125RouteRouteWithChildren
  '/{-$locale}/$': typeof Char123LocaleChar125SplatRoute
  '/{-$locale}/404': typeof Char123LocaleChar125404Route
  '/{-$locale}/about': typeof Char123LocaleChar125AboutRoute
  '/{-$locale}/contact': typeof Char123LocaleChar125ContactRoute
  '/{-$locale}/privacy-policy': typeof Char123LocaleChar125PrivacyPolicyRoute
  '/{-$locale}/project9': typeof Char123LocaleChar125Project9Route
  '/{-$locale}/shinjiru': typeof Char123LocaleChar125ShinjiruRoute
  '/{-$locale}/terms-conditions': typeof Char123LocaleChar125TermsConditionsRoute
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/{-$locale}'
    | '/{-$locale}/$'
    | '/{-$locale}/404'
    | '/{-$locale}/about'
    | '/{-$locale}/contact'
    | '/{-$locale}/privacy-policy'
    | '/{-$locale}/project9'
    | '/{-$locale}/shinjiru'
    | '/{-$locale}/terms-conditions'
    | '/{-$locale}/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/{-$locale}/$'
    | '/{-$locale}/404'
    | '/{-$locale}/about'
    | '/{-$locale}/contact'
    | '/{-$locale}/privacy-policy'
    | '/{-$locale}/project9'
    | '/{-$locale}/shinjiru'
    | '/{-$locale}/terms-conditions'
    | '/{-$locale}'
  id:
    | '__root__'
    | '/{-$locale}'
    | '/{-$locale}/$'
    | '/{-$locale}/404'
    | '/{-$locale}/about'
    | '/{-$locale}/contact'
    | '/{-$locale}/privacy-policy'
    | '/{-$locale}/project9'
    | '/{-$locale}/shinjiru'
    | '/{-$locale}/terms-conditions'
    | '/{-$locale}/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Char123LocaleChar125RouteRoute: typeof Char123LocaleChar125RouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/{-$locale}': {
      id: '/{-$locale}'
      path: '/{-$locale}'
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/': {
      id: '/{-$locale}/'
      path: '/'
      fullPath: '/{-$locale}/'
      preLoaderRoute: typeof Char123LocaleChar125IndexRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/terms-conditions': {
      id: '/{-$locale}/terms-conditions'
      path: '/terms-conditions'
      fullPath: '/{-$locale}/terms-conditions'
      preLoaderRoute: typeof Char123LocaleChar125TermsConditionsRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/shinjiru': {
      id: '/{-$locale}/shinjiru'
      path: '/shinjiru'
      fullPath: '/{-$locale}/shinjiru'
      preLoaderRoute: typeof Char123LocaleChar125ShinjiruRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/project9': {
      id: '/{-$locale}/project9'
      path: '/project9'
      fullPath: '/{-$locale}/project9'
      preLoaderRoute: typeof Char123LocaleChar125Project9RouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/privacy-policy': {
      id: '/{-$locale}/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/{-$locale}/privacy-policy'
      preLoaderRoute: typeof Char123LocaleChar125PrivacyPolicyRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/contact': {
      id: '/{-$locale}/contact'
      path: '/contact'
      fullPath: '/{-$locale}/contact'
      preLoaderRoute: typeof Char123LocaleChar125ContactRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/about': {
      id: '/{-$locale}/about'
      path: '/about'
      fullPath: '/{-$locale}/about'
      preLoaderRoute: typeof Char123LocaleChar125AboutRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/404': {
      id: '/{-$locale}/404'
      path: '/404'
      fullPath: '/{-$locale}/404'
      preLoaderRoute: typeof Char123LocaleChar125404RouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/$': {
      id: '/{-$locale}/$'
      path: '/$'
      fullPath: '/{-$locale}/$'
      preLoaderRoute: typeof Char123LocaleChar125SplatRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
  }
}

interface Char123LocaleChar125RouteRouteChildren {
  Char123LocaleChar125SplatRoute: typeof Char123LocaleChar125SplatRoute
  Char123LocaleChar125404Route: typeof Char123LocaleChar125404Route
  Char123LocaleChar125AboutRoute: typeof Char123LocaleChar125AboutRoute
  Char123LocaleChar125ContactRoute: typeof Char123LocaleChar125ContactRoute
  Char123LocaleChar125PrivacyPolicyRoute: typeof Char123LocaleChar125PrivacyPolicyRoute
  Char123LocaleChar125Project9Route: typeof Char123LocaleChar125Project9Route
  Char123LocaleChar125ShinjiruRoute: typeof Char123LocaleChar125ShinjiruRoute
  Char123LocaleChar125TermsConditionsRoute: typeof Char123LocaleChar125TermsConditionsRoute
  Char123LocaleChar125IndexRoute: typeof Char123LocaleChar125IndexRoute
}

const Char123LocaleChar125RouteRouteChildren: Char123LocaleChar125RouteRouteChildren =
  {
    Char123LocaleChar125SplatRoute: Char123LocaleChar125SplatRoute,
    Char123LocaleChar125404Route: Char123LocaleChar125404Route,
    Char123LocaleChar125AboutRoute: Char123LocaleChar125AboutRoute,
    Char123LocaleChar125ContactRoute: Char123LocaleChar125ContactRoute,
    Char123LocaleChar125PrivacyPolicyRoute:
      Char123LocaleChar125PrivacyPolicyRoute,
    Char123LocaleChar125Project9Route: Char123LocaleChar125Project9Route,
    Char123LocaleChar125ShinjiruRoute: Char123LocaleChar125ShinjiruRoute,
    Char123LocaleChar125TermsConditionsRoute:
      Char123LocaleChar125TermsConditionsRoute,
    Char123LocaleChar125IndexRoute: Char123LocaleChar125IndexRoute,
  }

const Char123LocaleChar125RouteRouteWithChildren =
  Char123LocaleChar125RouteRoute._addFileChildren(
    Char123LocaleChar125RouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  Char123LocaleChar125RouteRoute: Char123LocaleChar125RouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
