/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShinjiruRouteImport } from './routes/shinjiru'
import { Route as Project9RouteImport } from './routes/project9'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const ShinjiruRoute = ShinjiruRouteImport.update({
  id: '/shinjiru',
  path: '/shinjiru',
  getParentRoute: () => rootRouteImport,
} as any)
const Project9Route = Project9RouteImport.update({
  id: '/project9',
  path: '/project9',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/project9': typeof Project9Route
  '/shinjiru': typeof ShinjiruRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/project9': typeof Project9Route
  '/shinjiru': typeof ShinjiruRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/project9': typeof Project9Route
  '/shinjiru': typeof ShinjiruRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/contact' | '/project9' | '/shinjiru'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/contact' | '/project9' | '/shinjiru'
  id: '__root__' | '/' | '/about' | '/contact' | '/project9' | '/shinjiru'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  Project9Route: typeof Project9Route
  ShinjiruRoute: typeof ShinjiruRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shinjiru': {
      id: '/shinjiru'
      path: '/shinjiru'
      fullPath: '/shinjiru'
      preLoaderRoute: typeof ShinjiruRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project9': {
      id: '/project9'
      path: '/project9'
      fullPath: '/project9'
      preLoaderRoute: typeof Project9RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  Project9Route: Project9Route,
  ShinjiruRoute: ShinjiruRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
